substitutions:
  _TERRAFORM_IMAGE: 'hashicorp/terraform'
  _TERRAFORM_VERSION: 'latest'
  _GHE_CONFIG_PATH: '/workspace/upload/Terraform_resources/non-prod'
  
timeout: '2700s'
logs_bucket: 'gs://project_code_samples'
steps:

- id: 'tf-init'
  name: '${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}'
  args: ['init']
  dir: '$_GHE_CONFIG_PATH'
  env:
    - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

- id: 'tf-format'
  name: '${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}'
  args: ['fmt', '-list=true', '-write=false', '-diff=true', '-check=true', '.']
  dir: '$_GHE_CONFIG_PATH'
  waitFor: ['tf-init']

- id: 'tf-validate'
  name: '${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}'
  args: ['validate']
  dir: '$_GHE_CONFIG_PATH'
  waitFor: ['tf-init']

- id: 'tf-plan'
  name: '${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}'
  args:
    - 'plan'
    - '-input=false'
    - '-lock=false'  # Consider removing this in production
  dir: '$_GHE_CONFIG_PATH'
  env:
    - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

- id: 'checkov-scan'
  name: 'bridgecrew/checkov:latest'
  entrypoint: 'checkov'
  args: ['-d', '.']
  dir: '$_GHE_CONFIG_PATH'

